title: Alexander Watson Counselling
description: Counselling in Stockport and online. A calm, thoughtful space to understand yourself more clearly and relate to life with greater steadiness.

url: "https://alexanderwatsoncounselling.co.uk"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-seo-tag
